name: YouTube Music Profile Update

on:
  schedule:
    # Update every 5 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update YouTube Music Widget
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: YouTube Music Profile Widget
        uses: iXenonN/YouTube-Music-Profile@v2.2.0
        with:
          # This requires a secret named BROWSER_JSON to be set in your repo settings
          header: '${{ secrets.BROWSER_JSON }}'
